from manim import *
config.pixel_height=1080
config.pixel_width=1920
config.frame_height=9
config.frame_width=16



class Slide1Intro(Scene):
    def construct(self):
        plane=NumberPlane()
        #self.add(plane)
        title = Text('Algebraic Expressions',font_size=72)
        self.play(Write(title))
        self.wait(2)
        self.play(FadeOut(title))
class Slide2AimAndWorking(Scene):
    def construct(self):
        aim = Tex("Aim: To determine the factorisation of the Algebraic expression ","$a^2-2ab+b^2$").scale(0.8)
        self.play(Write(aim))
        self.wait(1)
        self.play(aim.animate.to_corner(UL))
        self.add(aim)
        self.wait(3)

        consider = Text("Consider,").scale(0.6).move_to([-6.5,3,0])
        self.play(Write(consider))
        step1 = MathTex("a^2-2ab+b^2=","aa-2ab+bb")
        step1[0].move_to([-4.1,2,0])
        self.play(Write(step1[0]),run_time=2)
        self.wait(1.5)
        step1[1].next_to(step1[0],RIGHT)
        self.play(Write(step1[1]),run_time=2)
        self.wait(0.5)

        step2=MathTex("=", "a","a", "-", "a","b", "-", "a","b" ,"+" ,"b","b")
        step2.move_to([-0.6,1,0])
        self.play(Write(step2),run_time=2)
        self.wait(1)
        self.play(Indicate(step2[1]),Indicate(step2[2]),Indicate(step2[4]),Indicate(step2[5]))
        self.wait()
        self.play(Indicate(step2[1]),Indicate(step2[4]))
        self.wait()
        step3 = MathTex("=","a","(a-b)","-","(a-b)","b").move_to([-0.5,0,0])
        self.play(Write(step3[0]),Write(step3[1]),Write(step3[2]),run_time=1.5)
        self.wait(0.3)
        self.play(Indicate(step2[7]),Indicate(step2[8]),Indicate(step2[10]),Indicate(step2[11]))
        self.wait()
        self.play(Indicate(step2[8]),Indicate(step2[11]))
        self.wait()
        self.play(Write(step3[3]),Write(step3[4]),Write(step3[5]),run_time=1.5)
        self.wait()
        self.play(Indicate(step3[3]))
        self.wait()
        self.play(Indicate(step3[2]),Indicate(step3[4]))
        self.wait()
        step4=MathTex("= (a-b)(a-b)").move_to([-1,-1,0])
        self.play(Write(step4),run_time=1.5)
        self.wait(0.3)

        self.play(FadeOut(*self.mobjects))

class Slide3ConclusionSlide(Scene):
    def construct(self):
        conclusion = Text("Conclusion:").scale(0.6).move_to([-6,4,0])
        self.play(Write(conclusion))
        Identity1=MathTex("a^2-2ab+b^2=(a-b)(a-b)")
        Identity1.shift(UP)
        self.play(Identity1.animate.move_to([0,3,0]))
        self.wait(5)
        example = Tex(r"Example: Use the above identity to factorise ","$25x^2-20x+4$.").scale(0.9)
        example.move_to([-1.5,2,0])
        self.play(Write(example))
        solution = Text("Solution:").scale(0.7)
        solution.move_to([-6.5,1,0])
        self.play(Write(solution))
        Estep1 = Text(r"Step 1: Convert the first term in some power of 2.",font_size=30)
        Estep1.to_edge(LEFT)
        Estep1.shift(RIGHT)
        self.play(Write(Estep1))
        Estep1Calculation = MathTex("25x^2=5 \\times 5 \\times x \\times x  = 5^2 \\times x^2 = (5 \\times x)^2 = (5x)^2")
        Estep1Calculation.to_edge(LEFT)
        Estep1Calculation.shift(RIGHT*1.5+DOWN)
        self.play(Write(Estep1Calculation),run_time=3)
        Estep2 = Text(r"Step 2: Convert the last term in some power of 2.",font_size=30)
        Estep2.to_edge(LEFT)
        Estep2.shift(RIGHT+DOWN*2)
        self.play(Write(Estep2))
        Estep2Calculation = MathTex("4 = 2 \\times 2 = (2)^2")
        Estep2Calculation.to_edge(DOWN)
        Estep2Calculation.shift(UP)
        self.play(Write(Estep2Calculation),run_time=2)
        self.play(FadeOut(*self.mobjects))
        Estep3Calculation = Text("Step 3: (Verification step) Verify the obtained values. ")
        Estep3_0 = Tex(r"Take,"," $a = 5x $"," and ","$b=2$"," and calculate,",font_size=37)
        Estep3_0.to_corner(UL)
        self.play(Write(Estep3_0))
        Estep3_1 = MathTex("2ab = 2 \\times 5x \\times 4 = 2 \\times 5 \\times 2 \\times x = 20x ")
        Estep3_1.to_edge(LEFT)
        Estep3_1.shift(UP*3+RIGHT*3)
        self.play(Write(Estep3_1),run_time=3)
        self.wait()
        Estep3_2 = Tex('''Which is equal to our remaining term. Hence, our choice is correct''',font_size=37)
        Estep3_2.to_edge(LEFT)
        Estep3_2.shift(UP*2)
        self.play(Write(Estep3_2),run_time=3)
        Estep3_3 = Tex("Therefore,",font_size=37)
        Estep3_3.to_edge(LEFT)
        Estep3_3.shift(UP*1.5)
        self.play(Write(Estep3_3))
        Estep3_4 = Tex(r"$25x^2-25x+4 = (a-b)(a-b) = (5x-2)(5x-2)$")
        self.play(Write(Estep3_4))
        self.wait()
        Estep3_5 = Tex(r"$25x^2-20x+4 = (5x-2)(5x-2)$")
        self.play(Transform(Estep3_4,Estep3_5),buff=0.5)
        self.play(FadeOut(*self.mobjects))
class Slide4OutroSlide(Scene):
    def construct(self):
        title = Text('Thanks for Watching',font_size=72)
        self.play(Write(title))
        self.wait(2)
        self.play(FadeOut(title))

class Slide0Thumbnail(Scene):
    def construct(self):
        Heading = Text("Algebraic Expressions").scale(1.5)
        Topic = Tex("Factorisation of  "," $a^2-2ab+b^2$")
        Heading.shift(UP)
        Topic.shift(DOWN)
        self.add(Heading,Topic)

